language: node_js

node_js:
  - 9
  - 8

services:
  - docker

before_install:
  - docker pull mysql:5.7
  - docker pull docker.elastic.co/elasticsearch/elasticsearch:6.2.2
  - docker run -p 4000:3306 -e MYSQL_ROOT_PASSWORD=test -e MYSQL_DATABASE=mysql_es_test -d mysql:5.7 --server-id=1 --log-bin=/var/lib/mysql/mysql-bin.log --binlog-format=row
  - docker run -p 4001:9200 -p 4002:9300 -e "discovery.type=single-node" -d docker.elastic.co/elasticsearch/elasticsearch:6.2.2
  
before_script:
  - sleep 10

script:
  - npm test --coverage

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js